{
	"version": 1520009158,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bestscore-sheet0.png",
		"images/taptostart-sheet0.png",
		"images/wall-sheet0.png",
		"images/player-sheet0.png",
		"images/balltrail-sheet0.png",
		"images/enemyspawner1-sheet0.png",
		"images/obstacle-sheet0.png",
		"images/particles.png",
		"images/destroy-sheet0.png",
		"images/block-sheet0.png",
		"images/score.png",
		"images/bestscorefont.png",
		"images/playersprite-sheet0.png",
		"images/wallshake-sheet0.png",
		"images/wallbg.png",
		"images/particles2.png",
		"images/tutorial-sheet0.png",
		"media/end.ogg",
		"media/switch.ogg",
		"media/cash register (ambient).ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}